Repository software-mansion/react-native-executorch, pull requests merged in 2025-08, with the labels that each got.

#491 feat: Simplify s2t app
  .cspell-wordlist.txt
  apps/speech-to-text/components/TextInputModal.tsx
  apps/speech-to-text/ios/Podfile.lock
  apps/speech-to-text/package.json
  apps/speech-to-text/screens/SpeechToTextScreen.tsx
  docs/docs/02-hooks/01-natural-language-processing/useSpeechToText.md
  yarn.lock
Labels: documentation, enhancement

#522 Fix: stop yarn typecheck from creating `.js` files inside project.
  packages/react-native-executorch/package.json
Labels: bug

#517 feat: implement whisper-streaming
  .cspell-wordlist.txt
  apps/llm/app/voice_chat/index.tsx
  apps/speech-to-text/screens/SpeechToTextScreen.tsx
  docs/docs/02-hooks/01-natural-language-processing/useSpeechToText.md
  docs/docs/03-typescript-api/01-natural-language-processing/SpeechToTextModule.md
  docs/docs/04-benchmarks/inference-time.md
  docs/docs/04-benchmarks/memory-usage.md
  docs/docs/04-benchmarks/model-size.md
  packages/react-native-executorch/common/rnexecutorch/models/speech_to_text/MoonshineStrategy.cpp
  packages/react-native-executorch/common/rnexecutorch/models/speech_to_text/MoonshineStrategy.h
  packages/react-native-executorch/common/rnexecutorch/models/speech_to_text/SpeechToText.cpp
  packages/react-native-executorch/common/rnexecutorch/models/speech_to_text/SpeechToText.h
  packages/react-native-executorch/common/rnexecutorch/models/speech_to_text/SpeechToTextStrategy.h
  packages/react-native-executorch/common/rnexecutorch/models/speech_to_text/WhisperStrategy.cpp
  packages/react-native-executorch/common/rnexecutorch/models/speech_to_text/WhisperStrategy.h
  packages/react-native-executorch/src/constants/modelUrls.ts
  packages/react-native-executorch/src/constants/sttDefaults.ts
  packages/react-native-executorch/src/controllers/SpeechToTextController.ts
  packages/react-native-executorch/src/hooks/natural_language_processing/useSpeechToText.ts
  packages/react-native-executorch/src/index.ts
  packages/react-native-executorch/src/modules/natural_language_processing/SpeechToTextModule.ts
  packages/react-native-executorch/src/types/stt.ts
  packages/react-native-executorch/src/utils/SpeechToTextModule/ASR.ts
  packages/react-native-executorch/src/utils/SpeechToTextModule/OnlineProcessor.ts
  packages/react-native-executorch/src/utils/SpeechToTextModule/hypothesisBuffer.ts
Labels: documentation, enhancement

#520 docs: fixed docs useImageSegmentation
  docs/docs/02-hooks/02-computer-vision/useClassification.md
  docs/docs/02-hooks/02-computer-vision/useImageEmbeddings.md
  docs/docs/02-hooks/02-computer-vision/useImageSegmentation.md
  docs/docs/02-hooks/02-computer-vision/useObjectDetection.md
  docs/docs/02-hooks/02-computer-vision/useStyleTransfer.md
  docs/docs/03-typescript-api/02-computer-vision/ClassificationModule.md
  docs/docs/03-typescript-api/02-computer-vision/ImageEmbeddingsModule.md
  docs/docs/03-typescript-api/02-computer-vision/ImageSegmentationModule.md
  docs/docs/03-typescript-api/02-computer-vision/ObjectDetectionModule.md
  docs/docs/03-typescript-api/02-computer-vision/StyleTransferModule.md
Labels: documentation

#564 Fix: Resource Fetcher not loading downloaded models
  packages/react-native-executorch/src/utils/ResourceFetcherUtils.ts
Labels: bug
